PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?r ?type ?label ?rGeo ?rGeoWKT 
WHERE { 
   GRAPH <http://localhost:3030/geographica/lgd> { 
      ?r rdf:type ?type. 
	   OPTIONAL{ ?r rdfs:label ?label }. 
	   ?r <http://linkedgeodata.org/ontology/hasGeometry> ?rGeo. 
	   ?rGeo <http://linkedgeodata.org/ontology/asWKT> ?rGeoWKT. 
      FILTER(geof:sfIntersects(?rGeoWKT, "null"^^<http://www.opengis.net/ont/geosparql#wktLiteral>)).
   } 
}