PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX geonames: <http://www.geonames.org/ontology#>

SELECT ?f ?name ?geo ?wkt 
WHERE { 
   GRAPH <http://localhost:3030/geographica/geonames> { 
      ?f geonames:name ?name;
         <http://www.geonames.org/ontology#hasGeometry> ?geo.
	   ?geo <http://www.geonames.org/ontology#asWKT> ?wkt.
      FILTER(?name = "TΓ‘lis"^^xsd:string) 
   }
}
