PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

SELECT (geof:convexHull(?o1) AS ?ret) 
WHERE { 
	GRAPH <http://localhost:3030/geographica/clc> {
		?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1
	} 
} 