#Query 2 - SC3_Relaxed_Geometries_Intersect_Geometries:

PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#>  
PREFIX lgd: <http://data.linkedeodata.eu/ontology#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?s1 ?s2
  GRAPH <http://localhost:3030/geographica/scalability> {
WHERE {
 ?s1 geo:hasGeometry [ geo:asWKT ?o1 ] ;
    lgd:has_code "1001"^^xsd:integer .
 ?s2 geo:hasGeometry [ geo:asWKT ?o2 ] ;
    lgd:has_code ?code2 .
 FILTER(?code2 IN (5622, 5601, 5641, 5621, 5661)) .
 FILTER(geof:sfIntersects(?o1, ?o2)).
} 
  }