PREFIX strdf: <http://strdf.di.uoa.gr/ontology#> 

SELECT (strdf:extent(?o1) AS ?ret)
WHERE {  
	GRAPH <http://localhost:3030/geographica/gag> {
		?s1 <http://geo.linkedopendata.gr/gag/ontology/asWKT> ?o1
	} 
}