PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

SELECT (geof:union(?o1) AS ?ret) 
WHERE {  
	GRAPH <http://localhost:3030/geographica/gag> {
		?s1 <http://geo.linkedopendata.gr/gag/ontology/asWKT> ?o1
	} 
}