#Query 7 - Synthetic_Selection_Intersects_512_0.25:

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX strdf: <http://strdf.di.uoa.gr/ontology#> 
PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 
PREFIX geo: <http://www.opengis.net/ont/geosparql#> 
PREFIX geo-sf: <http://www.opengis.net/ont/sf#> 
PREFIX landOwnership: <http://geographica.di.uoa.gr/generator/landOwnership/>

SELECT ?s1 
WHERE {
	GRAPH <http://localhost:3030/geographica/syntetic> {
  ?s1 landOwnership:hasGeometry ?s1Geo . 
  ?s1Geo landOwnership:asWKT ?geo1 . 
  ?s1 landOwnership:hasTag ?tag1 . 
  ?tag1 landOwnership:hasKey "512" .  
  FILTER(geof:sfIntersects(?geo1, "POLYGON ((0.0 0.0, 45.07667166562743 0.0, 45.07667166562743 39.01658593939718, 0.0 39.01658593939718, 0.0 0.0))"^^geo:wktLiteral)) .
    }
}
